# on: 
#   push:
#     branches:
#       - main

# jobs:
#   release-on-push:
#     runs-on: ubuntu-latest
#     env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     steps:
#       - name: Tag/Release on Push Action
#         uses: rymndhng/release-on-push-action@v0.27.0
#         with:
#           bump_version_scheme: minor
